# Generated by Django 2.1 on 2018-08-06 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_auto_20180806_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
