# Generated by Django 2.1 on 2018-08-06 03:11

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20180806_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='order_placed', max_length=50),
        ),
    ]
