# Generated by Django 2.1 on 2018-08-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_auto_20180811_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
    ]
