# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_auto_20170810_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='quantity',
        ),
    ]
